// Code generated by "stringer -type ErrorClass -trimprefix ErrorClass -tags static"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorClassNone-0]
	_ = x[ErrorClassNoMemory-1]
	_ = x[ErrorClassOS-2]
	_ = x[ErrorClassInvalid-3]
	_ = x[ErrorClassReference-4]
	_ = x[ErrorClassZlib-5]
	_ = x[ErrorClassRepository-6]
	_ = x[ErrorClassConfig-7]
	_ = x[ErrorClassRegex-8]
	_ = x[ErrorClassOdb-9]
	_ = x[ErrorClassIndex-10]
	_ = x[ErrorClassObject-11]
	_ = x[ErrorClassNet-12]
	_ = x[ErrorClassTag-13]
	_ = x[ErrorClassTree-14]
	_ = x[ErrorClassIndexer-15]
	_ = x[ErrorClassSSL-16]
	_ = x[ErrorClassSubmodule-17]
	_ = x[ErrorClassThread-18]
	_ = x[ErrorClassStash-19]
	_ = x[ErrorClassCheckout-20]
	_ = x[ErrorClassFetchHead-21]
	_ = x[ErrorClassMerge-22]
	_ = x[ErrorClassSSH-23]
	_ = x[ErrorClassFilter-24]
	_ = x[ErrorClassRevert-25]
	_ = x[ErrorClassCallback-26]
	_ = x[ErrorClassRebase-29]
	_ = x[ErrorClassPatch-31]
}

const (
	_ErrorClass_name_0 = "NoneNoMemoryOSInvalidReferenceZlibRepositoryConfigRegexOdbIndexObjectNetTagTreeIndexerSSLSubmoduleThreadStashCheckoutFetchHeadMergeSSHFilterRevertCallback"
	_ErrorClass_name_1 = "Rebase"
	_ErrorClass_name_2 = "Patch"
)

var (
	_ErrorClass_index_0 = [...]uint8{0, 4, 12, 14, 21, 30, 34, 44, 50, 55, 58, 63, 69, 72, 75, 79, 86, 89, 98, 104, 109, 117, 126, 131, 134, 140, 146, 154}
)

func (i ErrorClass) String() string {
	switch {
	case 0 <= i && i <= 26:
		return _ErrorClass_name_0[_ErrorClass_index_0[i]:_ErrorClass_index_0[i+1]]
	case i == 29:
		return _ErrorClass_name_1
	case i == 31:
		return _ErrorClass_name_2
	default:
		return "ErrorClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
